version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/nestjs-graphql-survey/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

survey-db:
  image: mysql:latest
  container_name: survey-db
  restart: always
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - TZ=Asia/Seoul
